export const types = {
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',
    LOGIN_VALIDATE_ERROR: 'LOGIN_VALIDATE_ERROR',
    LOGIN_VALIDATE_SUCCESS: 'LOGIN_VALIDATE_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',


    // Usuarios
    GET_ALL_USER: 'GET_ALL_USER',
    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_ERROR: 'GET_ALL_USER_ERROR',
    GET_USER:'GET_USER',
    GET_USER_SUCCESS:'GET_USER_SUCCESS',
    GET_USER_ERROR:'GET_USER_ERROR',
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_ERROR: 'CREATE_USER_ERROR',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',

    GET_ALL_ROLE: 'GET_ALL_ROLE',
    GET_ALL_ROLE_SUCCESS: 'GET_ALL_ROLE_SUCCESS',
    GET_ALL_ROLE_ERROR: 'GET_ALL_ROLE_ERROR',
    CREATE_ROLE:'CREATE_ROLE',
    CREATE_ROLE_SUCCESS:'CREATE_ROLE_SUCCESS',
    CREATE_ROLE_ERROR:'CREATE_ROLE_ERROR',
    GET_ROLE:'GET_ROLE',
    GET_ROLE_SUCCESS:'GET_ROLE_SUCCESS',
    GET_ROLE_ERROR:'GET_ROLE_ERROR',
    UPDATE_ROLE: 'UPDATE_ROLE',
    UPDATE_ROLE_SUCCESS: 'UPDATE_ROLE_SUCCESS',
    UPDATE_ROLE_ERROR: 'UPDATE_ROLE_ERROR',



    // Actividades
    GET_ALL_ACTIVIDAD: 'GET_ALL_ACTIVIDAD',
    GET_ALL_ACTIVIDAD_SUCCESS: 'GET_ALL_ACTIVIDAD_SUCCESS',
    GET_ALL_ACTIVIDAD_ERROR: 'GET_ALL_ACTIVIDAD_ERROR',

    // Niveles
    GET_ALL_NIVEL: 'GET_ALL_NIVEL',
    GET_ALL_NIVEL_SUCCESS: 'GET_ALL_NIVEL_SUCCESS',
    GET_ALL_NIVEL_ERROR: 'GET_ALL_NIVEL_ERROR',
    CREATE_NIVEL: 'CREATE_NIVEL',
    CREATE_NIVEL_SUCCESS: 'CREATE_NIVEL_SUCCESS',
    CREATE_NIVEL_ERROR: 'CREATE_NIVEL_ERROR',

    // Zonas
    GET_ALL_ZONA: 'GET_ALL_ZONA',
    GET_ALL_ZONA_SUCCESS: 'GET_ALL_ZONA_SUCCESS',
    GET_ALL_ZONA_ERROR: 'GET_ALL_ZONA_ERROR',

    // Centro de costos
    GET_ALL_CENTRO_COSTO: 'GET_ALL_CENTRO_COSTO',
    GET_ALL_CENTRO_COSTO_SUCCESS: 'GET_ALL_CENTRO_COSTO_SUCCESS',
    GET_ALL_CENTRO_COSTO_ERROR: 'GET_ALL_CENTRO_COSTO_ERROR',
}